#!/usr/bin/env bash

set -e

head_line_no=665
filename="app 138.json"

cur=20
to=4

id_offset=28

let tail_line_no=$head_line_no+1

while [ $cur -gt $to ]; do
  t="$(mktemp)"
  head -n $head_line_no "$filename" > "$t"
  echo $t
  let id=$cur+$id_offset
  cat <<EOF >>$t
        ,{
          "title": "$cur: GC tiers / generations",
          "error": false,
          "span": 3,
          "editable": true,
          "type": "graph",
          "id": $id,
          "datasource": null,
          "renderer": "flot",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "short",
            "short"
          ],
          "grid": {
            "leftMax": null,
            "rightMax": null,
            "leftMin": null,
            "rightMin": null,
            "threshold1": null,
            "threshold2": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "lines": true,
          "fill": 0,
          "linewidth": 1,
          "points": false,
          "pointradius": 5,
          "bars": false,
          "stack": false,
          "percentage": false,
          "legend": {
            "show": true,
            "values": false,
            "min": false,
            "max": false,
            "current": false,
            "total": false,
            "avg": false
          },
          "nullPointMode": "null",
          "steppedLine": false,
          "tooltip": {
            "value_type": "cumulative",
            "shared": true
          },
          "targets": [
            {
              "target": "aliasSub(movingAverage(application_1417724823159_0138.$cur.jvm.pools.*.usage, 10), '^.*\\\\.([^.]*)\\\\.usage.*', '\\\\1')"
            }
          ],
          "aliasColors": {},
          "seriesOverrides": [
            {
              "alias": "Code-Cache"
            }
          ],
          "links": []
        }
EOF


  tail -n +$tail_line_no "$filename" >> "$t"
  mv "$t" "$filename"
  let cur=$cur-1

done
