#!/usr/bin/env bash

# Retrieve a dashboard's JSON from the dashboard server, print it raw, and then print the
# unescaped "dashboard" JSON that is the main interesting part of the former.

set -e

usage() {
  echo "Usage: $0 -s <elasticsearch dashboard server host:port> <app id or name>" 1>&2
  exit 1
}

this_dir="$(dirname "${BASH_SOURCE[0]}")"
. "$this_dir"/get-dashboard-server

curl -s "$dashboard_server_url" | ./parse-dashboard-json
