#!/usr/bin/env bash

id="$1"
shift
filename="$id".json

echo "$filename"

./make-dashboard-json.js "$id" "$@" > "$filename"

curl -T "$filename" http://demeter-login2.demeter.hpc.mssm.edu:9200/grafana-dash/dashboard/

