#!/usr/bin/env bash

# PUT a dashboard JSON file to the dashboard server, thereby creating a dashboard that Grafana can
# load.

set -e

usage() {
  echo "Usage: $0 <app id or name>" 1>&2
  exit 1
}

this_dir="$(dirname "${BASH_SOURCE[0]}")"
. "$this_dir"/get-dashboard-server

filename="$dashboard_id".json

echo "PUTting dashboard file: $filename"

./make-dashboard-json "$dashboard_id" "$@" > "$filename"

curl -T "$filename" "$dashboard_server_dir"/
echo ''
